/**
 * Server-side singleton that loads the processed sponsor dataset from
 * prisma/data/sponsors-slim.json (generated by scripts/import-data.py).
 *
 * Falls back to an empty array if the file doesn't exist yet so the app
 * still boots during development before the import has been run.
 *
 * NEVER import this from client components — it reads the filesystem.
 */

import fs from "fs";
import path from "path";
import zlib from "zlib";
import type { Sponsor } from "@/lib/types";

// ── Tier / activity helpers ────────────────────────────────────────────────

export type SponsorTier = "Platinum" | "Gold" | "Silver" | "Bronze" | "Active" | "Inactive";
export type HiringActivity = "Very High" | "High" | "Medium" | "Low" | "Inactive";
export type SortKey = "relevance" | "cos" | "strength" | "opportunity" | "az";

export interface RichSponsor extends Sponsor {
  routes: string[];
  ratingType: string;
  sponsorTier: SponsorTier;
  hiringActivity: HiringActivity;
  sponsorStrengthScore: number;
  opportunityScore: number;
  cos2025Total: number | null;
  cos2025Sw: number | null;
  cos2025Gbm: number | null;
  cos2025SwSuppressed: boolean;
  cos2025GbmSuppressed: boolean;
}

export interface SearchParams {
  q?: string;
  industries?: string[];
  cities?: string[];
  routes?: string[];
  tiers?: string[];
  activities?: string[];
  aRatedOnly?: boolean;
  minCos?: number;
  sort?: SortKey;
}

export interface CityStatRecord {
  cityName: string;
  normalised: string;
  totalSponsors: number;
  cos2025Total: number;
  topIndustry: string | null;
  topRoute: string | null;
  tierBreakdown: Record<string, number>;
}

export interface RouteStatRecord {
  route: string;
  slug: string;
  totalSponsors: number;
  cos2025Total: number;
  topCities: Array<{ city: string; count: number }>;
}

// ── Module-level singletons (loaded once per process) ──────────────────────

let _sponsors: RichSponsor[] | null = null;
let _cityStats: CityStatRecord[] | null = null;
let _routeStats: RouteStatRecord[] | null = null;

function dataPath(file: string) {
  return path.join(process.cwd(), "prisma", "data", file);
}

function loadJson<T>(file: string, fallback: T): T {
  // Try gzipped version first, then plain JSON
  const gzPath = dataPath(file + ".gz");
  const jsonPath = dataPath(file);

  try {
    if (fs.existsSync(gzPath)) {
      const buf = zlib.gunzipSync(fs.readFileSync(gzPath));
      return JSON.parse(buf.toString("utf-8")) as T;
    }
    if (fs.existsSync(jsonPath)) {
      return JSON.parse(fs.readFileSync(jsonPath, "utf-8")) as T;
    }
  } catch {
    // fall through to fallback
  }
  return fallback;
}

export function getSponsors(): RichSponsor[] {
  if (_sponsors) return _sponsors;
  _sponsors = loadJson<RichSponsor[]>("sponsors-slim.json", []);
  return _sponsors;
}

export function getCityStats(): CityStatRecord[] {
  if (_cityStats) return _cityStats;
  _cityStats = loadJson<CityStatRecord[]>("city-stats.json", []);
  return _cityStats;
}

export function getRouteStats(): RouteStatRecord[] {
  if (_routeStats) return _routeStats;
  _routeStats = loadJson<RouteStatRecord[]>("route-stats.json", []);
  return _routeStats;
}

// ── Search ────────────────────────────────────────────────────────────────

function scoreMatch(s: RichSponsor, q: string): number {
  if (!q) return s.opportunityScore;
  const name = s.organisationName.toLowerCase();
  const qLower = q.toLowerCase();
  if (name === qLower) return 200;
  if (name.startsWith(qLower)) return 150 + s.opportunityScore;
  if (name.includes(qLower)) return 100 + s.opportunityScore;
  if (s.town.toLowerCase().includes(qLower)) return 50 + s.opportunityScore;
  if (s.industryCategory.toLowerCase().includes(qLower)) return 30 + s.opportunityScore;
  return -1;
}

export function searchSponsors(params: SearchParams): RichSponsor[] {
  const {
    q = "",
    industries = [],
    cities = [],
    routes = [],
    tiers = [],
    activities = [],
    aRatedOnly = false,
    minCos = 0,
    sort = "relevance",
  } = params;

  let results = getSponsors();

  // ── Filters ──
  if (q) {
    const qLower = q.toLowerCase();
    results = results.filter((s) => {
      const name = s.organisationName.toLowerCase();
      return (
        name.includes(qLower) ||
        s.town.toLowerCase().includes(qLower) ||
        s.county.toLowerCase().includes(qLower) ||
        s.industryCategory.toLowerCase().includes(qLower) ||
        s.routes.some((r) => r.toLowerCase().includes(qLower))
      );
    });
  }

  if (industries.length > 0) {
    results = results.filter((s) => industries.includes(s.industryCategory));
  }

  if (cities.length > 0) {
    const citiesLower = cities.map((c) => c.toLowerCase());
    results = results.filter((s) => citiesLower.includes(s.town.toLowerCase()));
  }

  if (routes.length > 0) {
    results = results.filter((s) =>
      routes.some((r) => s.routes.some((sr) => sr.toLowerCase().includes(r.toLowerCase())))
    );
  }

  if (tiers.length > 0) {
    results = results.filter((s) => tiers.includes(s.sponsorTier));
  }

  if (activities.length > 0) {
    results = results.filter((s) => activities.includes(s.hiringActivity));
  }

  if (aRatedOnly) {
    results = results.filter((s) => s.rating === "A");
  }

  if (minCos > 0) {
    results = results.filter((s) => (s.cos2025Total ?? 0) >= minCos);
  }

  // ── Sort ──
  switch (sort) {
    case "cos":
      results = [...results].sort(
        (a, b) => (b.cos2025Total ?? 0) - (a.cos2025Total ?? 0)
      );
      break;
    case "strength":
      results = [...results].sort(
        (a, b) => b.sponsorStrengthScore - a.sponsorStrengthScore
      );
      break;
    case "opportunity":
      results = [...results].sort(
        (a, b) => b.opportunityScore - a.opportunityScore
      );
      break;
    case "az":
      results = [...results].sort((a, b) =>
        a.organisationName.localeCompare(b.organisationName)
      );
      break;
    default: {
      // relevance: score-match if q, else opportunity desc
      if (q) {
        results = [...results]
          .map((s) => ({ s, score: scoreMatch(s, q) }))
          .filter(({ score }) => score >= 0)
          .sort((a, b) => b.score - a.score)
          .map(({ s }) => s);
      } else {
        results = [...results].sort(
          (a, b) => b.opportunityScore - a.opportunityScore
        );
      }
      break;
    }
  }

  return results;
}

export function getSponsorById(id: string): RichSponsor | undefined {
  return getSponsors().find((s) => s.id === id);
}

export function getSimilarSponsors(sponsor: RichSponsor, limit = 4): RichSponsor[] {
  return getSponsors()
    .filter(
      (s) =>
        s.id !== sponsor.id &&
        (s.industryCategory === sponsor.industryCategory ||
          s.town.toLowerCase() === sponsor.town.toLowerCase()) &&
        s.sponsorTier !== "Inactive"
    )
    .sort((a, b) => b.opportunityScore - a.opportunityScore)
    .slice(0, limit);
}

// ── Derived lists for filters ──────────────────────────────────────────────

let _industryList: string[] | null = null;
let _cityList: string[] | null = null;
let _routeList: string[] | null = null;

export function getIndustryList(): string[] {
  if (_industryList) return _industryList;
  const set = new Set<string>();
  for (const s of getSponsors()) set.add(s.industryCategory);
  _industryList = Array.from(set).sort();
  return _industryList;
}

export function getCityList(): string[] {
  if (_cityList) return _cityList;
  const counts = new Map<string, number>();
  for (const s of getSponsors()) {
    if (s.town) counts.set(s.town, (counts.get(s.town) ?? 0) + 1);
  }
  _cityList = Array.from(counts.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 50)
    .map(([c]) => c);
  return _cityList;
}

export function getRouteList(): string[] {
  if (_routeList) return _routeList;
  const set = new Set<string>();
  for (const s of getSponsors()) s.routes.forEach((r) => set.add(r));
  _routeList = Array.from(set).sort();
  return _routeList;
}

// ── Platform-level stats ──────────────────────────────────────────────────

export interface PlatformStats {
  totalSponsors: number;
  platinumSponsors: number;
  goldSponsors: number;
  totalCos2025: number;
  topCity: string;
}

let _platformStats: PlatformStats | null = null;

export function getPlatformStats(): PlatformStats {
  if (_platformStats) return _platformStats;
  const all = getSponsors();
  const totalCos = all.reduce((sum, s) => sum + (s.cos2025Total ?? 0), 0);
  const cityCount = new Map<string, number>();
  for (const s of all) {
    if (s.town) cityCount.set(s.town, (cityCount.get(s.town) ?? 0) + 1);
  }
  const topCity = Array.from(cityCount.entries()).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "London";
  _platformStats = {
    totalSponsors: all.length,
    platinumSponsors: all.filter((s) => s.sponsorTier === "Platinum").length,
    goldSponsors: all.filter((s) => s.sponsorTier === "Gold").length,
    totalCos2025: totalCos,
    topCity,
  };
  return _platformStats;
}
